twig:
    file_name_pattern: '*.twig'
    globals:
        bootstrap: 
            version: 5
            css_url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css'
        paths:
            '%kernel.project_dir%/templates': ~
        strict_variables: false
    form_themes:
        - 'bootstrap_5_layout.html.twig'

when@test:
    twig:
        strict_variables: true
